# Generated by Django 4.1.5 on 2023-01-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="discount",
            new_name="discount_price",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="name",
            new_name="item_name",
        ),
    ]
